# Generated by Django 5.2.16 on 2026-08-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_frames',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='user_lvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=256, null=True, unique=True, verbose_name='email address'),
        ),
    ]
