# Generated by Django 5.2.16 on 2026-08-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_user_frames_user_user_lvl_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bd_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='kislek54@example.com', max_length=256, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
