# Generated by Django 5.2.16 on 2026-08-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_bd_date_user_sex_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='achievement',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.achievement'),
        ),
    ]
