# Generated by Django 5.2.16 on 2026-08-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_achievement_user_achievement'),
        ('movies', '0025_reviewreply_replyvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='users', to='movies.movie'),
        ),
    ]
