# Generated by Django 5.2.16 on 2026-09-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_country_code'),
        ('movies', '0033_delete_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searsh_query', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='achievement',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='accounts.achievement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='search_history',
            field=models.ManyToManyField(blank=True, related_name='search_history', to='accounts.searchhistory'),
        ),
    ]
