# Generated by Django 5.2.16 on 2026-09-20 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_searchhistory_alter_user_achievement_and_more'),
        ('movies', '0033_delete_searchhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='searsh_query',
        ),
        migrations.RemoveField(
            model_name='user',
            name='search_history',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='query',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='achievement',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.achievement'),
        ),
        migrations.AlterField(
            model_name='user',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='users', to='movies.movie'),
        ),
    ]
