# Generated by Django 5.2.16 on 2026-07-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-rate', 'name']},
        ),
    ]
