# Generated by Django 5.2.16 on 2026-07-26 09:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('text', models.TextField()),
                ('contains_spoiler', models.BooleanField(blank=True, default=False)),
                ('likes', models.PositiveSmallIntegerField(default=0, verbose_name='Number of likes')),
                ('dislikes', models.PositiveSmallIntegerField(default=0, verbose_name='Number of dislikes')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-likes', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_moview_review')],
            },
        ),
    ]
