# Generated by Django 5.2.16 on 2026-07-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_review_avg_rating_movie_avg_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='avg_rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
