# Generated by Django 5.2.16 on 2026-07-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
