# Generated by Django 5.2.16 on 2026-07-29 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_review_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_public',
        ),
    ]
