# Generated by Django 5.2.16 on 2026-08-01 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_review_characters_rating_review_execution_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='characters_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='execution_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='idea_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='sound_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
