# Generated by Django 5.2.16 on 2026-08-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_review_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avg_rating',
        ),
    ]
