# Generated by Django 5.2.16 on 2026-08-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_review_avg_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['all_reviews', '-rate', 'name']},
        ),
        migrations.AddField(
            model_name='movie',
            name='all_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
