# Generated by Django 5.2.16 on 2026-08-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_alter_movie_options_movie_all_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-all_reviews', '-rate', 'name']},
        ),
    ]
