# Generated by Django 5.2.16 on 2026-08-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_alter_movie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-rate', 'name']},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='all_reviews',
        ),
    ]
