# Generated by Django 5.2.16 on 2026-08-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_alter_movie_options_remove_movie_all_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='path',
            new_name='cover',
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='movie_covers/'),
        ),
    ]
