# Generated by Django 5.2.16 on 2026-08-11 08:39

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_remove_movie_path_movie_cover'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
