# Generated by Django 5.2.16 on 2026-08-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_reviewreply_replyvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='wikidata_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
