# Generated by Django 5.2.16 on 2026-08-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_movie_cover_url_movie_imdb_id_movie_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='wikidata_name',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='movie',
            name='wikidata_description',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
