# Generated by Django 5.2.16 on 2026-08-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_movie_wikidata_name_alter_movie_wikidata_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
