# Generated by Django 5.2.16 on 2026-08-29 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_add_parler_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='WatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WILL_WATCH', "I'll watch it"), ('VIEWED', 'Viewed'), ('NOT_INTERESTING', "I'm not interested"), ('WATCHING', "I'm watching it right now"), ('DROPPED', 'I dropped watching it'), ('REWATCHING', 'Rewatching')], default='WILL_WATCH', max_length=20)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_statuses', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'movie'), name='unique_movie_status')],
            },
        ),
    ]
