# Generated by Django 5.2.16 on 2026-09-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0032_searchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
