# Generated by Django 5.2.16 on 2026-09-25 11:48

from django.contrib.postgres.operations import TrigramExtension
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('movies', '0033_delete_searchhistory'),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='GlobalSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('search_text', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_text'], name='global_search_trgm_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
