# Generated by Django 5.2.16 on 2026-09-25 11:48

from django.contrib.postgres.operations import TrigramExtension
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('movies', '0033_delete_searchhistory'),
    ]

    operations = [
        TrigramExtension(),
    ]
